baseURL = 'https://wxc900211.github.io/'
languageCode = 'en-us'
title = 'Welcome to Xiaochen Ideas'
theme = 'LoveIt'

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false